<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../BackendTest.Application/BackendTest.Application.csproj" />
    <ProjectReference Include="../BackendTest.Domain/BackendTest.Domain.csproj" />
  </ItemGroup>
</Project>
